name: CI

on:
  push:
    tags:
      - '*'
    #branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.12.0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          
	  - name: Install dependencies
      - run: opam install . --deps-only

	  - name: Build doculib
      - run: opam exec -- dune build

	  - name: Rename binary
	    run: mv _build/default/doculib.exe _build/default/doculib
		
      - name: Save binary (macOS)
	  	if: matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v2
        with:
          name: doculib-${{ github.ref_name }}-${{ runner.os }}-x86_64
          path: _build/default/doculib

	  - name: Build package (debian)
	  	if: matrix.os == 'ubuntu-latest'
		run: mkdir release/packages
		run: bash release/release_amd64.sh
		uses: actions/upload-artifact@v2
		with:
		  name: doculib-${{ github.ref_name }}-${{ runner.os }}-x86_64
		  path: release/packages/doculib_*_amd64.deb
		  